import * as THREE from './vendor/three.module.js';
const PAPER='#e8e6dd',INK='#191919',RED='#f04429',ACID='#d6ed49';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const canvas=document.createElement('canvas');canvas.id='archive';canvas.tabIndex=0;canvas.setAttribute('aria-label','Julien Robinson spatial portfolio. Tab to navigate, Enter to open, Escape to close. Drag to rotate.');
document.body.append(canvas);
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){canvas.remove();throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(PAPER);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),ui=new THREE.Scene(),archive=new THREE.Group();scene.add(archive);
const camera=new THREE.OrthographicCamera(-10,10,5,-5,.1,100),uiCamera=camera.clone();camera.position.z=25;uiCamera.position.z=30;
scene.add(new THREE.HemisphereLight(0xffffff,0x79766c,3));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(-5,9,12);scene.add(key);
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2(99,99),clock=new THREE.Clock();
const targets=[],uiTargets=[],items=[];
let W=16,H=10,mobile=false,current='',selected=null,hovered=null,drag=null,dragged=false,turn=0,tilt=0,shuffled=false,lastTime=0;
let pointer={x:0,y:0},sculpture=null,detail=null,detailTargets=[],sound=false,audioCtx=null;
const sections=['index','projects','about','experience','skills'],names=['INDEX','SELECTED WORK','PROFILE','EXPERIENCE','CAPABILITIES'];
const descriptions={index:'An independent collection of systems, experiments & ideas.',projects:'Public code. Open experiments. Work in progress.',about:'Software engineer. Mauritius, Indian Ocean.',experience:'A timeline of building things that people use.',skills:'Tools are useful. Knowing how they connect is everything.'};
const projects=[
 {title:'SATAT',code:'01',category:'DART / FLUTTER',subtitle:'A table for four.',body:'A real-time adaptation of the Mauritian four-player trick-taking card game. Built with Flutter.',repo:'satat',art:'cards',color:RED},
 {title:'LOCAL SITE',code:'02',category:'JAVASCRIPT / FLASK',subtitle:'A personal playground.',body:'An experimental space for galleries, a curriculum vitae, and a browser game. Small ideas, made tangible.',repo:'localsite',art:'window',color:'#719097'},
 {title:'THIS SPACE',code:'03',category:'JAVASCRIPT / THREE.JS',subtitle:'An archive you can touch.',body:'A portfolio treated as a collection of physical objects. Typography, navigation and compositions rendered in real time.',repo:'anonymoususer17.github.io',art:'type',color:PAPER},
 {title:'ALGO MANUAL',code:'04',category:'C / ALGORITHMS',subtitle:'Thinking in structures.',body:'Programming exercises from The Algorithm Design Manual. Working through problems, one structure at a time.',repo:'algo-design-manual',art:'graph',color:ACID},
 {title:'ADVENT 2024',code:'05',category:'PYTHON / PUZZLES',subtitle:'December, decoded.',body:'Python solutions to the opening Advent of Code puzzles. An exercise in curiosity and problem-solving.',repo:'advent-of-code-2024',art:'grid',color:'#c1b6d0'},
 {title:'PROJECT EULER',code:'06',category:'C / MATHEMATICS',subtitle:'Patterns beneath numbers.',body:'Compact C solutions to early Project Euler challenges. Mathematics translated into small, deliberate programs.',repo:'eulerproject',art:'orbit',color:'#c8c4b8'}
];
function ctx(w=1024,h=1024){const c=document.createElement('canvas');c.width=w;c.height=h;return[c,c.getContext('2d')];}
function texture(c){const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return t;}
function type(g,text,x,y,size=20,color=INK,font='Arial',weight='400',align='left'){g.fillStyle=color;g.font=`${weight} ${size}px ${font}`;g.textAlign=align;g.textBaseline='top';g.fillText(text,x,y);}
function rule(g,x,y,w){g.fillStyle=INK;g.fillRect(x,y,w,1);}
function wrap(g,text,x,y,width,size=25,line=1.3){g.font=`400 ${size}px Arial`;g.textAlign='left';g.textBaseline='top';g.fillStyle=INK;let row='',yy=y;for(const word of text.split(' ')){const next=row+word+' ';if(g.measureText(next).width>width&&row){g.fillText(row,x,yy);yy+=size*line;row=word+' ';}else row=next;}g.fillText(row,x,yy);return yy+size*line;}
function grain(g,w,h){let seed=714;g.fillStyle='rgba(0,0,0,.06)';for(let i=0;i<16000;i++){seed=(seed*16807)%2147483647;const x=seed%w;seed=(seed*16807)%2147483647;g.fillRect(x,seed%h,1,1);}}
function plane(c,w,h){return new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:texture(c),side:THREE.DoubleSide}));}
function label(text,w,h,{size=38,color=INK,align='left',weight='400',font='Arial'}={}){const[c,g]=ctx(1024,Math.round(1024*h/w));if(font==='monospace')size=Math.max(size,1024*(mobile?.14:.115)/w);size=Math.min(size,c.height-8);type(g,text,align==='center'?512:align==='right'?1024:0,4,size,color,font,weight,align);const m=plane(c,w,h);m.material.transparent=true;m.material.depthTest=false;return m;}
function textAt(parent,text,x,y,w,h,opts={}){const m=label(text,w,h,opts);m.position.set(x,y,0);parent.add(m);return m;}
function lineAt(parent,x,y,w){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,.008),new THREE.MeshBasicMaterial({color:INK}));m.position.set(x,y,0);parent.add(m);}
function tick(freq=210){if(!sound)return;try{audioCtx ||=new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.5,audioCtx.currentTime+.09);g.gain.setValueAtTime(.04,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.1);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.11);}catch{}}
function art(g,kind,x,y,w,h,color){g.save();g.beginPath();g.rect(x,y,w,h);g.clip();g.translate(x,y);g.fillStyle=color;g.fillRect(0,0,w,h);
 if(kind==='cards'){for(let i=0;i<4;i++){g.save();g.translate(w*.5+(i-1.5)*w*.13,h*.55);g.rotate((i-1.5)*.22);g.fillStyle=i===2?INK:PAPER;g.shadowColor='#0006';g.shadowBlur=10;g.fillRect(-w*.17,-h*.35,w*.34,h*.69);g.shadowBlur=0;type(g,['A','K','Q','J'][i],-w*.14,-h*.31,w*.065,i===2?PAPER:INK,'Georgia');type(g,['♠','♥','♣','♦'][i],0,-h*.1,w*.19,i===2?PAPER:INK,'Arial','400','center');g.restore();}}
 else if(kind==='window'){for(let i=0;i<7;i++){g.fillStyle=i%2?PAPER:INK;g.fillRect(w*.12+i*18,h*.12+i*25,w*.57,h*.49);g.fillStyle=color;g.fillRect(w*.12+i*18+4,h*.12+i*25+23,w*.57-8,h*.49-27);type(g,'○ ○ ○',w*.12+i*18+8,h*.12+i*25+5,10,i%2?INK:PAPER);}}
 else if(kind==='type'){g.translate(w*.5,h*.5);g.rotate(-.1);for(let i=0;i<5;i++)type(g,'JR',-w*.44,-h*.53+i*h*.18,w*.51,i===2?RED:INK,'Arial','900');}
 else if(kind==='graph'){const pts=[];for(let i=0;i<19;i++){const a=i*2.399,r=Math.sqrt(i)*w*.085;pts.push([w*.5+Math.cos(a)*r,h*.5+Math.sin(a)*r]);}g.strokeStyle=INK;g.lineWidth=1.5;for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++)if((i+j)%4===0){g.beginPath();g.moveTo(...pts[i]);g.lineTo(...pts[j]);g.stroke();}pts.forEach((p,i)=>{g.beginPath();g.fillStyle=i%3===0?RED:INK;g.arc(...p,i%3===0?11:5,0,Math.PI*2);g.fill();});}
 else if(kind==='grid'){const cell=w/9;for(let i=0;i<9;i++)for(let j=0;j<9;j++){g.fillStyle=(i*7+j*3)%11<5?INK:((i+j)%3?color:PAPER);g.fillRect(i*cell+2,j*cell+2,cell-4,cell-4);if((i+j)%4===0)type(g,String(i*9+j).padStart(2,'0'),i*cell+8,j*cell+8,17,PAPER,'monospace');}}
 else if(kind==='orbit'){g.strokeStyle=INK;g.lineWidth=1.2;for(let i=0;i<35;i++){g.beginPath();g.ellipse(w*.5,h*.5,w*.36,h*(.05+i*.011),i*.08,0,Math.PI*2);g.stroke();}g.fillStyle=RED;g.beginPath();g.arc(w*.5,h*.5,w*.07,0,Math.PI*2);g.fill();}g.restore();}
function poster(p){const[c,g]=ctx(768,1024);g.fillStyle=PAPER;g.fillRect(0,0,768,1024);type(g,`JR—${p.code}                  PUBLIC ARCHIVE`,38,30,17,INK,'monospace');rule(g,38,67,692);art(g,p.art,38,94,692,674,p.color);type(g,p.title,34,797,p.title.length>11?65:78,INK,'Arial','900');rule(g,38,898,692);type(g,p.category,38,923,18,INK,'monospace');type(g,'↗',690,915,39);grain(g,768,1024);return c;}
function shadow(w,h){const[c,g]=ctx(128,128),gr=g.createRadialGradient(64,64,8,64,64,64);gr.addColorStop(0,'rgba(0,0,0,.2)');gr.addColorStop(1,'rgba(0,0,0,0)');g.fillStyle=gr;g.fillRect(0,0,128,128);const m=plane(c,w*1.4,h*1.3);m.material.transparent=true;m.material.depthWrite=false;m.position.set(.17,-.25,-.28);return m;}
function object(c,w,h,id,action){const group=new THREE.Group();group.add(shadow(w,h));group.add(new THREE.Mesh(new THREE.BoxGeometry(w,h,.045),new THREE.MeshStandardMaterial({color:0xd2cfc4,roughness:.83})));const front=plane(c,w,h);front.position.z=.026;group.add(front);archive.add(group);const item={group,front,w,h,id,action,base:new THREE.Vector3(),target:new THREE.Vector3(),rot:new THREE.Vector3(),targetRot:new THREE.Vector3(),targetScale:1,hover:0};front.userData.item=item;targets.push(front);items.push(item);return item;}
function pose(a,x,y,z,rz=0,ry=0){a.base.set(x,y,z);a.target.copy(a.base);a.targetRot.set(0,ry,rz);a.rot.copy(a.targetRot);a.group.position.set(x,y-2,z-8);a.group.rotation.set(.4,ry,rz-.1);a.group.scale.setScalar(.65);}
function sheet(title,number,sub,color,kind){const[c,g]=ctx(768,1024);g.fillStyle=color;g.fillRect(0,0,768,1024);type(g,`0${number} / COLLECTION`,35,30,19,INK,'monospace');rule(g,35,65,698);
 if(kind==='disc'){g.strokeStyle=INK;for(let i=0;i<45;i++){g.beginPath();g.arc(384,425,45+i*5.2,0,Math.PI*2);g.stroke();}g.fillStyle=RED;g.beginPath();g.arc(384,425,47,0,Math.PI*2);g.fill();}
 else if(kind==='timeline'){for(let i=0;i<3;i++){g.save();g.translate(50+i*200,200+i*110);g.rotate(-.07);g.fillStyle=i===1?RED:INK;g.fillRect(0,0,180,400);type(g,['19','20','23'][i],15,25,100,PAPER,'Arial','900');g.restore();}}
 else if(kind==='profile'){g.save();g.translate(384,420);g.rotate(-.13);type(g,'J',-270,-270,570,INK,'Georgia');type(g,'R',-10,-170,450,RED,'Georgia');g.restore();}else art(g,'graph',0,80,768,660,color);
 type(g,title,32,790,title.length>9?66:85,INK,'Arial','900');rule(g,35,902,698);type(g,sub,35,927,20,INK,'monospace');type(g,'↗',684,916,44);grain(g,768,1024);return c;}
function kinetic(){sculpture=new THREE.Group();for(let i=0;i<16;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(.11,2.4,.15),new THREE.MeshStandardMaterial({color:0x202020,roughness:.24,metalness:.72}));m.rotation.z=i*Math.PI/16;sculpture.add(m);}const ring=new THREE.Mesh(new THREE.TorusGeometry(.76,.026,8,100),new THREE.MeshBasicMaterial({color:RED}));ring.rotation.x=.8;sculpture.add(ring);archive.add(sculpture);}
function clear(group){group.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of(Array.isArray(o.material)?o.material:[o.material])){m.map?.dispose();m.dispose();}});group.clear();}
function route(){const s=location.pathname.split('/').pop().replace('.html','');return sections.includes(s)?s:'index';}
function build(section){clear(archive);targets.length=0;items.length=0;selected=null;sculpture=null;current=section;shuffled=false;turn=tilt=0;document.title=`${section==='index'?'Julien Robinson':names[sections.indexOf(section)]+' — Julien Robinson'} / Software Engineer`;const span=Math.min(W-1.4,15.6);
 if(section==='index'){const entries=[['WORK',1,'SIX PUBLIC EXPERIMENTS',PAPER,'disc','projects'],['PROFILE',2,'MAURITIUS / 20° S',ACID,'profile','about'],['EXPERIENCE',3,'2019 — PRESENT','#d9d3c7','timeline','experience'],['TOOLKIT',4,'SYSTEMS & CONNECTIONS',RED,'graph','skills']];const pw=mobile?Math.min((W-1.15)/2,2.7):Math.min(span/4.7,3.1),ph=pw*1.333;entries.forEach((e,i)=>{const a=object(sheet(...e.slice(0,5)),pw,ph,e[5],()=>navigate(e[5]));pose(a,mobile?(i%2-.5)*(pw+.28):(i-1.5)*(pw+.52),mobile?.15+(i<2?ph*.52:-ph*.54):-.6+[.1,-.22,.17,-.12][i],i*.12,[.085,-.08,.055,-.085][i],(i-1.5)*-.08);});if(!mobile){kinetic();sculpture.scale.setScalar(.75);sculpture.position.set(span/2-.5,2.6,-1);}}
 else if(section==='projects'){const pw=mobile?Math.min((W-1.1)/2,2.2):Math.min(span/3.7,2.3),ph=pw*1.333;projects.forEach((p,i)=>{const a=object(poster(p),pw,ph,p.repo,()=>inspect(a,p));pose(a,mobile?(i%2-.5)*(pw+.23):(i%3-1)*(pw+1.45),mobile?(1-Math.floor(i/2))*(ph+.26)-.2:(.5-Math.floor(i/3))*(ph+.3)-.35,(i%3)*.12,[.06,-.06,.045,-.045,.05,-.045][i],(i%3-1)*-.05);});}
 else if(section==='about'){const[c,g]=ctx(950,1150);g.fillStyle=ACID;g.fillRect(0,0,950,1150);type(g,'PERSONAL FILE / 001',50,38,20,INK,'monospace');rule(g,50,78,850);type(g,'JULIEN',42,115,142,INK,'Arial','900');type(g,'ROBINSON',42,252,139,INK,'Arial','900');type(g,'Software engineer, Mauritius.',50,437,39,INK,'Georgia');wrap(g,'Working across public digital services and enterprise applications. Building the systems behind the everyday.',50,527,800,39);rule(g,50,759,850);type(g,'CURRENT',50,788,18,INK,'monospace');wrap(g,'Economic Development Board Mauritius',270,784,610,27);type(g,'EDUCATION',50,900,18,INK,'monospace');wrap(g,'BSc Software Engineering, University of Mauritius · 2020',270,894,600,25);type(g,'EN / FR / MAURITIAN CREOLE',50,1060,20,INK,'monospace');grain(g,950,1150);const pw=mobile?W-1.3:5.2,ph=pw*1150/950;const a=object(c,pw,ph,'profile',()=>{turn+=.25;tick();});pose(a,mobile?0:-2.5,-.2,0,-.025);if(!mobile){kinetic();sculpture.scale.setScalar(1.9);sculpture.position.set(4,.5,1);textAt(archive,'20° 09′ S  /  57° 30′ E',4,-2.5,4,.3,{size:40,font:'monospace'});}}
 else if(section==='experience'){const jobs=[['2019','GOVERNMENT\nONLINE CENTRE','Intern','Government web forms. PHP, JavaScript, SOAP and InfoHighway.',PAPER],['2020—23','INFOMIL\nMAURITIUS','Software Engineer','Back-office applications. C#, VB.NET, Angular, SQL and .NET Core.',ACID],['2023—NOW','ECONOMIC\nDEVELOPMENT\nBOARD','Software Engineer','National E-Licensing System. Angular 5/19, Java, IBM BPM and DB2.',RED]];jobs.forEach((p,i)=>{const[c,g]=ctx(800,1100);g.fillStyle=p[4];g.fillRect(0,0,800,1100);type(g,'CAREER RECORD / 0'+(i+1),40,34,20,INK,'monospace');rule(g,40,80,720);type(g,p[0],35,125,p[0].length>5?94:145,INK,'Arial','900');p[1].split('\n').forEach((s,j)=>type(g,s,38,400+j*64,62,INK,'Arial','900'));type(g,p[2],40,685,30,INK,'Georgia');rule(g,40,760,720);wrap(g,p[3],40,798,700,32);type(g,i===2?'ONGOING ↗':'ARCHIVED',40,1030,20,INK,'monospace');grain(g,800,1100);const pw=mobile?W-1.5:Math.min(span/3.5,3.8),ph=mobile?2.6:pw*1.375;const a=object(c,pw,ph,'career-'+i,()=>inspect(a,{title:p[1].replaceAll('\n',' '),category:p[0],subtitle:p[2],body:p[3]}));pose(a,mobile?0:(i-1)*(pw+.6),mobile?(1-i)*2.85-.2:-.35,i*.25,(i-1)*-.045);});}
 else{const stacks=[['FRONTEND',['Angular 5—19','TypeScript','JavaScript','HTML / CSS'],RED],['BACKEND',['C# / .NET Core','Java','VB.NET','Python'],PAPER],['DATA & PROCESS',['SQL Server','IBM DB2','IBM BPM'],ACID]];stacks.forEach((p,i)=>{const[c,g]=ctx(800,1000);g.fillStyle=p[2];g.fillRect(0,0,800,1000);type(g,'CAPABILITY / 0'+(i+1),40,35,22,INK,'monospace');rule(g,40,80,720);type(g,['FE','BE','DB'][i],22,118,290,INK,'Arial','900');type(g,p[0],40,480,p[0].length>9?55:68,INK,'Arial','900');p[1].forEach((s,j)=>{rule(g,40,600+j*80,720);type(g,s,40,620+j*80,33);});grain(g,800,1000);const pw=mobile?W-1.5:Math.min(span/3.5,3.8),ph=mobile?2.6:pw*1.25;const a=object(c,pw,ph,'skill-'+i,()=>inspect(a,{title:p[0],category:'CAPABILITIES / 0'+(i+1),subtitle:'A connected practice.',body:p[1].join(' · ')}));for(let j=1;j<=3;j++){const b=new THREE.Mesh(new THREE.BoxGeometry(pw,ph,.03),new THREE.MeshStandardMaterial({color:p[2],roughness:.8}));b.position.set(j*.055,-j*.045,-j*.09);b.rotation.z=j*.025;a.group.add(b);}pose(a,mobile?0:(i-1)*(pw+.75),mobile?(1-i)*2.85-.2:-.35,i*.25,[.075,-.04,-.075][i],(i-1)*-.15);});}buildUI();syncAccess();}
function inspect(a,p){if(selected===a){close();return;}close();selected=a;tick(310);items.forEach(b=>{if(b!==a){b.target.z=-10;b.targetScale=.72;}});a.target.set(mobile?0:-W*.22,mobile?1.45:-.3,5);a.targetRot.set(0,0,0);a.targetScale=mobile?Math.min(1.1,2.7/a.h):Math.min(1.3,5.9/a.h);detail=new THREE.Group();ui.add(detail);const[c,g]=ctx(900,950);type(g,p.category,0,5,24,INK,'monospace');rule(g,0,61,880);wrap(g,p.title,0,103,875,76,1);type(g,p.subtitle,0,330,38,INK,'Georgia');wrap(g,p.body,0,419,860,31,1.5);rule(g,0,735,880);type(g,p.repo?'VIEW SOURCE ON GITHUB ↗':'RETURN TO COLLECTION ↙',0,786,27,INK,'monospace');type(g,'[ ESC TO CLOSE ]',0,889,21,INK,'monospace');const dw=mobile?W-1.15:Math.min(W*.39,6.3),dh=dw*950/900,panel=plane(c,dw,dh);panel.material.transparent=true;panel.material.depthTest=false;panel.position.set(mobile?0:W*.235,mobile?-2.4:-.3,0);detail.add(panel);const action=()=>p.repo?window.open('https://github.com/anonymoususer17/'+p.repo,'_blank','noopener,noreferrer'):close();const hit=new THREE.Mesh(new THREE.PlaneGeometry(dw,dh*.17),new THREE.MeshBasicMaterial({visible:false}));hit.position.set(panel.position.x,panel.position.y-dh*.36,2);hit.userData.action=action;detail.add(hit);detailTargets=[hit];buildUI();syncAccess(p,action);}
function close(){if(detail){clear(detail);ui.remove(detail);detail=null;}detailTargets=[];if(selected){items.forEach(a=>{a.target.copy(a.base);a.targetRot.copy(a.rot);a.targetScale=1;});selected=null;buildUI();syncAccess();}}
const uiGroup=new THREE.Group();ui.add(uiGroup);
function button(text,x,y,w,h,action,opts={}){const m=textAt(uiGroup,text,x,y,w,h,opts);const hit=new THREE.Mesh(new THREE.PlaneGeometry(w,Math.max(h,mobile?.62:.4)),new THREE.MeshBasicMaterial({visible:false}));hit.position.copy(m.position);hit.userData.action=action;uiGroup.add(hit);uiTargets.push(hit);return m;}
function buildUI(){clear(uiGroup);uiTargets.length=0;const left=-W/2+.42,right=W/2-.42,top=H/2-.38;button('JULIEN ROBINSON',left+1.65,top,3.3,.35,()=>navigate('index'),{size:60,weight:'900'});textAt(uiGroup,mobile?'SOFTWARE ENGINEER':'SOFTWARE ENGINEER / MAURITIUS',right-2,top,4,.26,{size:31,align:'right',font:'monospace'});lineAt(uiGroup,0,top-.38,W-.84);const nw=(W-.84)/5,navNames=mobile?['INDEX','WORK','PROFILE','CAREER','TOOLS']:names;navNames.forEach((n,i)=>button((current===sections[i]?'● ':'')+n,left+nw*(i+.5),top-.73,nw,.32,()=>navigate(sections[i]),{size:mobile?55:Math.min(58,nw*18),color:current===sections[i]?RED:INK,font:'monospace',align:i===4?'right':'left'}));if(current==='index'&&!selected){textAt(uiGroup,mobile?'SELECTED / INDEX':'SYSTEMS, OBJECTS',0,top-1.35,W-.84,.62,{size:mobile?69:78,font:'Georgia'});if(!mobile)textAt(uiGroup,'& OTHER EXPERIMENTS.',left+3.8,top-2.02,7.6,.38,{size:41,font:'Georgia'});}else if(!selected)textAt(uiGroup,descriptions[current],0,top-1.27,W-.84,.36,{size:mobile?34:26,font:'Georgia'});const bottom=-H/2+.34;lineAt(uiGroup,0,bottom+.4,W-.84);button(selected?'← CLOSE':'↻ REARRANGE',left+.95,bottom,1.9,.3,()=>selected?close():shuffle(),{size:mobile?65:49,font:'monospace'});if(!mobile)textAt(uiGroup,selected?'INSPECTING OBJECT':'DRAG TO ROTATE · CLICK TO EXPLORE',-.65,bottom,5.2,.26,{size:28,font:'monospace',align:'center'});button(sound?'SOUND ON':'SOUND OFF',right-2.35,bottom,1.6,.3,()=>{sound=!sound;tick();buildUI();},{size:mobile?63:45,font:'monospace',align:'right'});button('CONTACT ↗',right-.8,bottom,1.6,.3,()=>location.href='mailto:jberobinson.pro@gmail.com',{size:mobile?63:45,font:'monospace',align:'right'});}
function navigate(s,push=true){if(s===current){close();return;}tick(350);close();if(push)history.pushState({},'',s==='index'?'index.html':s+'.html');build(s);}
addEventListener('popstate',()=>navigate(route(),false));
function shuffle(){shuffled=!shuffled;tick(170);items.forEach((a,i)=>{if(shuffled){a.target.set(a.base.x+Math.sin(i*4.7)*.35,a.base.y+Math.cos(i*2.4)*.28,a.base.z+(i%2)*.5);a.targetRot.set((i%2?1:-1)*.1,(i%3-1)*.2,a.rot.z+Math.sin(i*3+1)*.2);}else{a.target.copy(a.base);a.targetRot.copy(a.rot);}});}
const access=document.createElement('nav');access.className='archive-accessible';access.setAttribute('aria-label','Spatial archive controls');document.body.append(access);
function syncAccess(p=null,action=null){
 access.replaceChildren();const status=document.createElement('p');status.className='archive-status';status.setAttribute('role','status');status.textContent=p?[p.title,p.category,p.subtitle,p.body].join('. '):names[sections.indexOf(current)]+'. '+descriptions[current];access.append(status);
 const add=(s,fn)=>{const b=document.createElement('button');b.textContent=s;b.onclick=fn;access.append(b);};sections.forEach((s,i)=>add(names[i],()=>navigate(s)));items.forEach(a=>add('Open '+a.id,a.action));if(selected){add('Close detail',close);if(p?.repo)add('View '+p.title+' on GitHub',action);}add('Rearrange objects',shuffle);add('Contact Julien',()=>location.href='mailto:jberobinson.pro@gmail.com');
 document.querySelectorAll('main a').forEach(a=>a.tabIndex=-1);
}
function updateMouse(e){const r=canvas.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);pointer={x:mouse.x,y:mouse.y};}
function hitTest(){ray.setFromCamera(mouse,uiCamera);const u=ray.intersectObjects([...detailTargets,...uiTargets]);if(u.length)return{action:u[0].object.userData.action};if(selected)return null;ray.setFromCamera(mouse,camera);const h=ray.intersectObjects(targets);if(h.length)return{item:h[0].object.userData.item,action:h[0].object.userData.item.action};return null;}
canvas.addEventListener('pointerdown',e=>{updateMouse(e);const item=hitTest()?.item;drag={x:e.clientX,y:e.clientY,turn,tilt,item,origin:item?.target.clone()};dragged=false;canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{updateMouse(e);if(drag&&!selected){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>7)dragged=true;if(dragged){if(drag.item){drag.item.target.x=THREE.MathUtils.clamp(drag.origin.x+dx/innerWidth*W,-W/2+drag.item.w/2,W/2-drag.item.w/2);drag.item.target.y=THREE.MathUtils.clamp(drag.origin.y-dy/innerHeight*H,-H/2+drag.item.h/2+.8,H/2-drag.item.h/2-1.8);}else{turn=THREE.MathUtils.clamp(drag.turn+dx*.002,-.5,.5);tilt=THREE.MathUtils.clamp(drag.tilt-dy*.0015,-.3,.3);}canvas.style.cursor='grabbing';}}});
canvas.addEventListener('pointerup',e=>{updateMouse(e);if(!dragged)hitTest()?.action?.();drag=null;canvas.releasePointerCapture(e.pointerId);});canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('pointerleave',()=>{if(!drag)mouse.set(99,99);});
addEventListener('keydown',e=>{if(e.key==='Escape'){close();turn=tilt=0;}if(e.key===' '&&e.target===canvas){e.preventDefault();shuffle();}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const i=sections.indexOf(current),d=e.key==='ArrowRight'?1:-1;navigate(sections[(i+d+sections.length)%sections.length]);}});
function resize(){if(detail){clear(detail);ui.remove(detail);detail=null;detailTargets=[];}mobile=innerWidth<700;H=mobile?12:10;W=H*innerWidth/innerHeight;renderer.setSize(innerWidth,innerHeight);for(const c of[camera,uiCamera]){c.left=-W/2;c.right=W/2;c.top=H/2;c.bottom=-H/2;c.updateProjectionMatrix();}build(current||route());}
let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(resize,100);});
function enrich(){
 for(const a of items){if(a.enriched)continue;a.enriched=true;
  if(mobile&&(current==='experience'||current==='skills')){
   const i=items.indexOf(a),[c,g]=ctx(900,580);const cols=current==='skills'?[RED,PAPER,ACID]:[PAPER,ACID,RED];g.fillStyle=cols[i];g.fillRect(0,0,900,580);
   const records=current==='skills'?[['FRONTEND','Angular 5—19 / TypeScript','JavaScript / HTML / CSS'],['BACKEND','C# / .NET Core / Java','VB.NET / Python'],['DATA & PROCESS','SQL Server / IBM DB2','IBM BPM']]:[['2019','Government Online Centre','Intern · PHP / JavaScript / SOAP'],['2020—23','Infomil Mauritius','Software Engineer · C# / Angular / SQL'],['2023—NOW','Economic Development Board','Software Engineer · Java / IBM BPM / DB2']];
   const r=records[i];type(g,'0'+(i+1)+' / '+(current==='skills'?'CAPABILITY':'CAREER RECORD'),40,30,24,INK,'monospace');rule(g,40,80,820);type(g,r[0],35,130,r[0].length>10?73:99,INK,'Arial','900');type(g,r[1],40,330,32);type(g,r[2],40,395,28);rule(g,40,480,820);type(g,'CLICK TO INSPECT ↗',40,515,22,INK,'monospace');grain(g,900,580);a.front.material.map.dispose();a.front.material.map=texture(c);
  }
  const kind=current==='index'?({projects:'disc',skills:'graph'}[a.id]):current==='projects'?projects.find(p=>p.repo===a.id)?.art:null;
  if(!['disc','cards','graph','orbit','window'].includes(kind))continue;
  const color=current==='index'?(a.id==='skills'?RED:PAPER):projects.find(p=>p.repo===a.id).color;
  const mask=new THREE.Mesh(new THREE.PlaneGeometry(a.w*.9,a.h*.65),new THREE.MeshBasicMaterial({color}));mask.position.set(0,a.h*.08,.032);a.group.add(mask);
  const model=new THREE.Group();model.position.set(0,a.h*.08,.075);model.scale.setScalar(a.w);a.group.add(model);a.model=model;a.kind=kind;
  const dark=new THREE.MeshStandardMaterial({color:0x181818,roughness:.32,metalness:.5});
  if(kind==='disc'){const disc=new THREE.Mesh(new THREE.CylinderGeometry(.36,.36,.025,80),dark);disc.rotation.x=Math.PI/2;model.add(disc);for(let i=0;i<17;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.11+i*.014,.0015,4,80),new THREE.MeshBasicMaterial({color:0x77776c}));ring.position.z=.018;model.add(ring);}const center=new THREE.Mesh(new THREE.CircleGeometry(.095,48),new THREE.MeshBasicMaterial({color:RED}));center.position.z=.02;model.add(center);}
  if(kind==='orbit'){for(let i=0;i<12;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(.32,.0025,4,70),dark);r.rotation.set(i*.24,i*.15,i*.05);model.add(r);}model.add(new THREE.Mesh(new THREE.SphereGeometry(.075,20,16),new THREE.MeshStandardMaterial({color:RED,roughness:.3})));}
  if(kind==='graph'){const pts=[];for(let i=0;i<13;i++){const theta=i*2.399,rad=.33*Math.sqrt(i/12);const p=new THREE.Vector3(Math.cos(theta)*rad,Math.sin(theta)*rad,Math.sin(i*3)*.15);pts.push(p);const n=new THREE.Mesh(new THREE.SphereGeometry(i%3===0?.019:.01,8,8),new THREE.MeshStandardMaterial({color:i%3===0?0xe83522:0x191919}));n.position.copy(p);model.add(n);}for(let i=0;i<13;i++)for(let j=i+1;j<13;j++)if((i+j)%3===0){const geo=new THREE.BufferGeometry().setFromPoints([pts[i],pts[j]]);model.add(new THREE.Line(geo,new THREE.LineBasicMaterial({color:INK,transparent:true,opacity:.7})));}}
  if(kind==='cards'){for(let i=0;i<4;i++){const[c,g]=ctx(280,400);g.fillStyle=i===2?INK:PAPER;g.fillRect(0,0,280,400);const col=i===2?PAPER:INK;type(g,['A','K','Q','J'][i],18,18,35,col,'Georgia');type(g,['♠','♥','♣','♦'][i],140,142,110,col,'Arial','400','center');const card=plane(c,.31,.48);card.position.set((i-1.5)*.12,0,i*.04);card.rotation.z=(i-1.5)*-.18;model.add(card);}}
  if(kind==='window'){for(let i=0;i<5;i++){const[c,g]=ctx(400,300);g.fillStyle=INK;g.fillRect(0,0,400,300);type(g,'○ ○ ○    LOCAL / 0'+i,12,10,17,PAPER,'monospace');g.fillStyle=color;g.fillRect(7,38,386,255);g.strokeStyle=PAPER;for(let j=0;j<9;j++){g.beginPath();g.moveTo(30,70+j*21);g.lineTo(360,70+j*21);g.stroke();}const screen=plane(c,.52,.39);screen.position.set((i-2)*.065,-(i-2)*.06,i*.05);model.add(screen);}}
 }
}
const scaleVector=new THREE.Vector3();
function frame(){const t=clock.getElapsedTime(),dt=Math.min(t-lastTime,.05);lastTime=t;const ease=reduced?1:1-Math.exp(-dt*9),hit=drag?null:hitTest(),next=hit?.item||null;if(next!==hovered){hovered=next;if(hovered)tick(150);}if(!drag)canvas.style.cursor=hit?'pointer':'grab';archive.rotation.y=THREE.MathUtils.lerp(archive.rotation.y,selected?0:turn+(reduced?0:pointer.x*.025),ease);archive.rotation.x=THREE.MathUtils.lerp(archive.rotation.x,selected?0:tilt+(reduced?0:-pointer.y*.018),ease);items.forEach((a,i)=>{a.hover=THREE.MathUtils.lerp(a.hover,hovered===a?1:0,ease);const f=reduced||selected?0:Math.sin(t*.6+i*1.7)*.045;a.group.position.x=THREE.MathUtils.lerp(a.group.position.x,a.target.x,ease);a.group.position.y=THREE.MathUtils.lerp(a.group.position.y,a.target.y+f+a.hover*.12,ease);a.group.position.z=THREE.MathUtils.lerp(a.group.position.z,a.target.z+a.hover*.6,ease);a.group.rotation.x=THREE.MathUtils.lerp(a.group.rotation.x,a.targetRot.x+(hovered===a?pointer.y*.06:0),ease);a.group.rotation.y=THREE.MathUtils.lerp(a.group.rotation.y,a.targetRot.y+(hovered===a?pointer.x*.06:0),ease);a.group.rotation.z=THREE.MathUtils.lerp(a.group.rotation.z,a.targetRot.z*(1-a.hover*.45),ease);a.group.scale.lerp(scaleVector.setScalar(a.targetScale+a.hover*.035),ease);});if(sculpture&&!reduced){sculpture.rotation.y=Math.sin(t*.2)*.45;sculpture.rotation.z=t*.035;}renderer.autoClear=true;renderer.render(scene,camera);renderer.autoClear=false;renderer.clearDepth();renderer.render(ui,uiCamera);}
scene.onBeforeRender=()=>{enrich();for(const a of items){if(selected&&a!==selected)a.target.x=a.base.x+(a.base.x>=0?W:-W);if(a.model){a.model.position.z=a.w*.2+.075+a.hover*.2;if(!reduced){const t=clock.elapsedTime;a.model.rotation.y=Math.sin(t*.6)*.12+a.hover*.22;a.model.rotation.x=Math.cos(t*.5)*.08;if(a.kind==='disc'||a.kind==='orbit')a.model.rotation.z=t*(a.kind==='disc'?.1:.065);}}}};
resize();renderer.setAnimationLoop(frame);document.documentElement.classList.add('archive-ready');document.addEventListener('visibilitychange',()=>renderer.setAnimationLoop(document.hidden?null:frame));canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();document.documentElement.classList.remove('archive-ready');canvas.style.display='none';});canvas.addEventListener('webglcontextrestored',()=>location.reload());
window.archiveStatus=()=>({section:current,objects:items.length,selected:selected?.id||null,drawCalls:renderer.info.render.calls,webgl:renderer.getContext().getParameter(renderer.getContext().VERSION)});
